#! BLUE
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: blue
type: Opaque
data:
  JWT_SECRET: c29tZXNlY3JldA== # Base64 encoded value of "somesecret"

---

#! GREEN
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: green
type: Opaque
data:
  JWT_SECRET: c29tZXNlY3JldA== # Base64 encoded value of "somesecret"