apiVersion: v1
kind: Secret
metadata:
  name: nps-mongodb-secret
  namespace: default
type: Opaque  #sets secret data is stored as encrypted bytes and can't be accessed in plain text within K8s.
data:
  mongo-init-db: bmNz   # Base64 encoded value of "nps"
  mongo-root-username: bnBzLWFkbWlu     # Base64 encoded value of nps-admin"
  mongo-root-password: UGFzc3dvcmQkMTM1   # Base64 encoded value of "Password$135"