apiVersion: apps/v1
kind: StatefulSet # Sets up MongoDB as a scalable and persistent StatefulSet.
metadata:
  name: nps-mongodb
  namespace: default
spec:
  replicas: 3
  serviceName: nps-mongodb-svc
  selector:
    matchLabels:
      app: nps-mongodb
  template:
    metadata:
      labels:
        app: nps-mongodb
    spec:
      containers:
      - name: nps-mongodb
        image: mongo:latest
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: nps-mongodb-secret
              key: mongo-root-username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nps-mongodb-secret
              key: mongo-root-password
        - name: MONGO_INITDB_DATABASE
          valueFrom:
            secretKeyRef:
              name: nps-mongodb-secret
              key: mongo-init-db
        volumeMounts:
        - name: nps-mongodb-data
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: nps-mongodb-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 50Gi

