apiVersion: apps/v1
kind: Deployment
metadata:
  name: authSvc
  namespace: nps-blue
spec:
  replicas: 3
  selector:
    matchLabels:
      app: authSvc
      version: blue
  template:
    metadata:
      labels:
        app: authSvc
        version: blue
    spec:
    containers:
      - name: authSvc
        image: my-docker-repo/mern-backend:latest
        ports:
        - containerPort: 3001
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: NODE_ENV
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: PORT
        - name: MONGO_URI
          value: mongodb://mongodb:27017/nps
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: JWT_SECRET




##########################################################
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: backend
#   namespace: green
# spec:
#   replicas: 3
#   selector:
#     matchLabels:
#       app: backend
#       version: green
#   template:
#     metadata:
#       labels:
#         app: backend
#         version: green
#     spec:
#       containers:
#       - name: backend
#         image: your-docker-repo/mern-backend:latest
#         ports:
#         - containerPort: 5000
#         env:
#         - name: NODE_ENV
#           valueFrom:
#             configMapKeyRef:
#               name: backend-config
#               key: NODE_ENV
#         - name: PORT
#           valueFrom:
#             configMapKeyRef:
#               name: backend-config
#               key: PORT
#         - name: MONGO_URI
#           value: mongodb://mongodb:27017/mydb
#         - name: JWT_SECRET
#           valueFrom:
#             secretKeyRef:
#               name: backend-secret
#               key: JWT_SECRET